name: Update AlphaXiv Folders

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 毎日0時(JST=9時)に実行

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch folders from AlphaXiv API
        env:
          TOKEN: ${{ secrets.ALPHAXIV_TOKEN }}
        run: |
          mkdir -p data
          curl -sS \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/json" \
            "https://api.alphaxiv.org/v1/users/6851b878e4d7cd843caec1c8/folders" \
            | jq . | tee data/folders.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Run formatter
        run: |
          npm install
          npm run format

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/folders.json FOLDERS.md
            git commit -m "chore: update folders"
            git push
          fi
